name: inno_model
description: Inno Model
version: 1.0.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  freezed_annotation: ^2.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  freezed: ^2.2.0
  build_runner: ^2.3.0
