name: inno_event
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  grpc: ^3.0.2
  protobuf: ^2.1.0
  uuid: ^3.0.6

  inno_database:
    git:
      url: https://github.com/innoapps-dev/innoapps
      path: packages/inno_database

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
