name: inno_core
description: Inno Core
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  grpc: ^3.0.2
  protobuf: ^2.0.0
  postgres: ^2.4.5
  uuid: ^3.0.6
  postgres_pool: ^2.1.3
  openid_client: ^0.4.6
  dotenv: ^4.1.0 

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
