name: inno_database
description: Inno Database
version: 1.0.3

publish_to: 'none'

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  postgres: ^2.6.1
  uuid: ^3.0.7
  postgres_pool: ^2.1.6
  fpdart: ^0.6.0
  dotenv: ^4.1.0
  logging: ^1.2.0

  inno_model:
    git:
      url: https://github.com/innoapps-dev/innoapps
      path: packages/inno_model

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  faker_dart: ^0.1.11

