name: inno_database
description: Inno Database
version: 1.0.3

publish_to: 'none'

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  postgres: ^2.5.2
  uuid: ^3.0.6
  postgres_pool: ^2.1.3
  openid_client: ^0.4.6
  protobuf: ^2.1.0
  fpdart: ^0.3.0
  # TODO: Switch to pub when https://github.com/mockturtl/dotenv/pull/34 is merged
  dotenv: 
    git:
      url: https://github.com/bettdouglas/dotenv.git
  logging: ^1.1.0

  inno_model:
    git:
      url: https://github.com/innoapps-dev/assessment-centre-innoapps
      path: packages/inno_model

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  faker_dart: ^0.1.11

