name: inno_file
description: Inno File
version: 1.0.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  grpc: ^3.0.2
  protobuf: ^2.1.0
  uuid: ^3.0.6

  inno_database:
    git:
      url: https://github.com/innoapps-dev/assessment-centre-innoapps
      path: packages/inno_database

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0